#!/usr/bin/env python3
from PIL import Image
import struct

im = Image.open("bootlogo.png").convert("RGBA")
w, h = im.size

with open("bootlogo.fb", "wb") as f:
    for row in range(0, h):
        for col in range(0, w // 8):
            v = 0
            for n in range(8):
                r, g, b, a = im.getpixel((col * 8 + n, h - row - 1))
                if r > 128 or g > 128 or b > 128:
                    v |= 1 << n
            f.write(struct.pack('B', v))
