name: PlasticPlayer3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  convert: ^3.1.2
  file_picker: ^8.1.7
  http_parser: ^4.0.2
  go_router: ^14.6.2
  dio: ^5.7.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
